export const mockCases = [
  {
    id: 'SRV-1042',
    category: 'Streetlight Repair',
    description: 'Streetlight out near the intersection of 3rd and Mission Streets.',
    address: '300 Mission St, San Francisco, CA',
    latitude: 37.7895,
    longitude: -122.3987,
    status: 'Open',
    priority_score: 91,
    pin_color: '#ff5d5d',
  },
  {
    id: 'SRV-1043',
    category: 'Pothole Repair',
    description: 'Large pothole causing traffic hazards during morning commute.',
    address: '1500 Market St, San Francisco, CA',
    latitude: 37.7743,
    longitude: -122.4173,
    status: 'In Progress',
    priority_score: 87,
    pin_color: '#ffb347',
  },
  {
    id: 'SRV-1044',
    category: 'Graffiti Removal',
    description: 'Fresh tagging reported on a public transit shelter.',
    address: '1000 Valencia St, San Francisco, CA',
    latitude: 37.7647,
    longitude: -122.4218,
    status: 'Open',
    priority_score: 64,
    pin_color: '#4db6ac',
  },
  {
    id: 'SRV-1045',
    category: 'Park Maintenance',
    description: 'Broken bench and overgrown hedge in Dolores Park.',
    address: '19th St & Dolores St, San Francisco, CA',
    latitude: 37.7596,
    longitude: -122.427,
    status: 'Scheduled',
    priority_score: 72,
    pin_color: '#4b8cf5',
  },
  {
    id: 'SRV-1046',
    category: 'Sidewalk Repair',
    description: 'Cracked sidewalk near a curb ramp that needs immediate attention.',
    address: '800 Pine St, San Francisco, CA',
    latitude: 37.7902,
    longitude: -122.411,
    status: 'Open',
    priority_score: 78,
    pin_color: '#ffd166',
  },
  {
    id: 'SRV-1047',
    category: 'Tree Maintenance',
    description: 'Dead tree limb hanging over a pedestrian path.',
    address: '1400 Haight St, San Francisco, CA',
    latitude: 37.7702,
    longitude: -122.4383,
    status: 'Pending Review',
    priority_score: 83,
    pin_color: '#a78bfa',
  },
];
